services:
  bot:
    build: .
    container_name: marzbot_app
    restart: on-failure
    # Убрали network_mode: host, теперь бот в одной сети с БД и Redis
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine
    container_name: marzbot_redis
    restart: always
    volumes:
      - "/var/lib/marzbot/docker-volumes/redis:/data"
    command: redis-server --appendonly yes --replica-read-only no

  mariadb:
    image: "mariadb:latest"
    container_name: marzbot_db
    restart: always
    volumes:
      - "/var/lib/marzbot/docker-volumes/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "1234ggg"
      MYSQL_DATABASE: "marzbot"
      MYSQL_USER: "marzbot"
      MYSQL_PASSWORD: "1234ggg"

  phpmyadmin:
    image: phpmyadmin
    container_name: marzbot_pma
    restart: always
    ports:
      - "8010:80"
    environment:
      - PMA_HOST=mariadb
